spring.application.name=photo-album-client
server.port=8020

spring.security.oauth2.client.registration.kiroffclient.client-id=kiroff-service-id
spring.security.oauth2.client.registration.kiroffclient.client-secret=kiroff-secret
spring.security.oauth2.client.registration.kiroffclient.scope=openid, profile, roles
spring.security.oauth2.client.registration.kiroffclient.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kiroffclient.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.kiroffclient.authorization-uri=http://localhost:8081/auth/realms/kiroff/protocol/openid-connect/auth
spring.security.oauth2.client.provider.kiroffclient.token-uri=http://localhost:8081/auth/realms/kiroff/protocol/openid-connect/token
spring.security.oauth2.client.provider.kiroffclient.jwk-set-uri=http://localhost:8081/auth/realms/kiroff/protocol/openid-connect/certs
spring.security.oauth2.client.provider.kiroffclient.user-info-uri=http://localhost:8081/auth/realms/kiroff/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.kiroffclient.user-name-attribute=preferred_username

eureka.client.service-url.defaultZone=http://localhost:8010/eureka
eureka.instance.instance-id=${spring.application.name}:${instanceId:${random.value}}